// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_message.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IPAddr               string   `protobuf:"bytes,2,opt,name=IPAddr,proto3" json:"IPAddr,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	SspID                string   `protobuf:"bytes,4,opt,name=SspID,proto3" json:"SspID,omitempty"`
	SlotID               string   `protobuf:"bytes,5,opt,name=SlotID,proto3" json:"SlotID,omitempty"`
	AppID                string   `protobuf:"bytes,6,opt,name=AppID,proto3" json:"AppID,omitempty"`
	AdType               string   `protobuf:"bytes,7,opt,name=AdType,proto3" json:"AdType,omitempty"`
	SspAppIdKey          string   `protobuf:"bytes,8,opt,name=SspAppIdKey,proto3" json:"SspAppIdKey,omitempty"`
	SspAppPlaceIdKey     string   `protobuf:"bytes,9,opt,name=SspAppPlaceIdKey,proto3" json:"SspAppPlaceIdKey,omitempty"`
	SspAppSecretKey      string   `protobuf:"bytes,10,opt,name=SspAppSecretKey,proto3" json:"SspAppSecretKey,omitempty"`
	Timestamp            string   `protobuf:"bytes,11,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Type                 string   `protobuf:"bytes,12,opt,name=Type,proto3" json:"Type,omitempty"`
	SID                  string   `protobuf:"bytes,13,opt,name=SID,proto3" json:"SID,omitempty"`
	Uuid                 string   `protobuf:"bytes,14,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c8fc4a27b8b845, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Request) GetIPAddr() string {
	if m != nil {
		return m.IPAddr
	}
	return ""
}

func (m *Request) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Request) GetSspID() string {
	if m != nil {
		return m.SspID
	}
	return ""
}

func (m *Request) GetSlotID() string {
	if m != nil {
		return m.SlotID
	}
	return ""
}

func (m *Request) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *Request) GetAdType() string {
	if m != nil {
		return m.AdType
	}
	return ""
}

func (m *Request) GetSspAppIdKey() string {
	if m != nil {
		return m.SspAppIdKey
	}
	return ""
}

func (m *Request) GetSspAppPlaceIdKey() string {
	if m != nil {
		return m.SspAppPlaceIdKey
	}
	return ""
}

func (m *Request) GetSspAppSecretKey() string {
	if m != nil {
		return m.SspAppSecretKey
	}
	return ""
}

func (m *Request) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetSID() string {
	if m != nil {
		return m.SID
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	ID                   string   `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data,omitempty"`
	IP                   string   `protobuf:"bytes,5,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_36c8fc4a27b8b845, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *Response) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Response) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterType((*Response)(nil), "grpc.Response")
}

func init() { proto.RegisterFile("grpc_message.proto", fileDescriptor_36c8fc4a27b8b845) }

var fileDescriptor_36c8fc4a27b8b845 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbf, 0x4d, 0x93, 0xfe, 0x98, 0xfe, 0xf8, 0x96, 0x41, 0x64, 0x11, 0x0f, 0xa5, 0xa7,
	0xe2, 0xa1, 0x82, 0x5e, 0xbc, 0x16, 0xe3, 0x61, 0x51, 0x21, 0x24, 0xf1, 0x2c, 0x31, 0x59, 0x42,
	0xa1, 0x6d, 0xd6, 0xdd, 0xed, 0xa1, 0x7f, 0xb5, 0xff, 0x82, 0xcc, 0x6c, 0xaa, 0xa2, 0xb7, 0xf7,
	0xde, 0x7c, 0x36, 0x0c, 0x6f, 0x02, 0x58, 0x1b, 0x5d, 0xbe, 0xee, 0x94, 0xb5, 0x45, 0xad, 0x56,
	0xda, 0x34, 0xae, 0xc1, 0x90, 0xb2, 0xc5, 0x47, 0x00, 0xfd, 0x54, 0xbd, 0x1f, 0x94, 0x75, 0x38,
	0x85, 0x40, 0xc6, 0xa2, 0x33, 0xef, 0x2c, 0x87, 0x69, 0x20, 0x63, 0x3c, 0x87, 0x9e, 0x4c, 0xd6,
	0x55, 0x65, 0x44, 0xc0, 0x59, 0xeb, 0x70, 0x06, 0xdd, 0x67, 0x5b, 0x8b, 0x2e, 0x87, 0x24, 0xf1,
	0x0c, 0xa2, 0xcc, 0x6a, 0x19, 0x8b, 0x90, 0x33, 0x6f, 0xe8, 0x7d, 0xb6, 0x6d, 0x9c, 0x8c, 0x45,
	0xe4, 0xdf, 0x7b, 0x47, 0xf4, 0x5a, 0x13, 0xdd, 0xf3, 0x34, 0x1b, 0xa2, 0xd7, 0x55, 0x7e, 0xd4,
	0x4a, 0xf4, 0x3d, 0xed, 0x1d, 0xce, 0x61, 0x94, 0x59, 0x4d, 0x4c, 0xf5, 0xa8, 0x8e, 0x62, 0xc0,
	0xc3, 0x9f, 0x11, 0x5e, 0xc1, 0xcc, 0xdb, 0x64, 0x5b, 0x94, 0xca, 0x63, 0x43, 0xc6, 0xfe, 0xe4,
	0xb8, 0x84, 0xff, 0x3e, 0xcb, 0x54, 0x69, 0x94, 0x23, 0x14, 0x18, 0xfd, 0x1d, 0xe3, 0x25, 0x0c,
	0xf3, 0xcd, 0x4e, 0x59, 0x57, 0xec, 0xb4, 0x18, 0x31, 0xf3, 0x1d, 0x20, 0x42, 0xc8, 0xbb, 0x8e,
	0x79, 0xc0, 0x9a, 0x7a, 0xc9, 0x64, 0x2c, 0x26, 0xbe, 0x97, 0x4c, 0xc6, 0x44, 0xbd, 0x1c, 0x36,
	0x95, 0x98, 0x7a, 0x8a, 0xf4, 0xa2, 0x82, 0x41, 0xaa, 0xac, 0x6e, 0xf6, 0x56, 0xd1, 0xfc, 0xbe,
	0xa9, 0x14, 0x77, 0x1e, 0xa5, 0xac, 0xe9, 0x2b, 0x0f, 0xe6, 0x54, 0x39, 0xc9, 0xf6, 0x2e, 0xdd,
	0xaf, 0xbb, 0x20, 0x84, 0x71, 0xe1, 0x8a, 0xb6, 0x6c, 0xd6, 0xcc, 0x24, 0x6d, 0xcf, 0x81, 0x4c,
	0x6e, 0xee, 0x20, 0xca, 0x4d, 0x51, 0x2a, 0xbc, 0x86, 0x71, 0x6e, 0x8a, 0xbd, 0xd5, 0x8d, 0x71,
	0x4f, 0x4d, 0x8d, 0x93, 0x15, 0xdd, 0x7d, 0xd5, 0xde, 0xfc, 0x62, 0x7a, 0xb2, 0x7e, 0xa3, 0xc5,
	0xbf, 0xb7, 0x1e, 0xff, 0x1e, 0xb7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x43, 0xb0, 0x7c,
	0x34, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TraceClient is the client API for Trace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TraceClient interface {
	TransportLog(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type traceClient struct {
	cc *grpc.ClientConn
}

func NewTraceClient(cc *grpc.ClientConn) TraceClient {
	return &traceClient{cc}
}

func (c *traceClient) TransportLog(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.Trace/TransportLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraceServer is the server API for Trace service.
type TraceServer interface {
	TransportLog(context.Context, *Request) (*Response, error)
}

func RegisterTraceServer(s *grpc.Server, srv TraceServer) {
	s.RegisterService(&_Trace_serviceDesc, srv)
}

func _Trace_TransportLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraceServer).TransportLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Trace/TransportLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraceServer).TransportLog(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Trace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Trace",
	HandlerType: (*TraceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransportLog",
			Handler:    _Trace_TransportLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_message.proto",
}
